language: python
#dist: trusty
jobs:
  include:
    - dist: trusty
      python: 3.6
    - dist: xenial
      python: 3.7
    - dist: bionic
      python: 3.8

#python:
#  - "2.7"
#  - "3.6"
#  - "3.7"
#  - "3.8"
# command to install dependencies
env:
  - TEST_SUITE: tests/suite1
  - TEST_SUITE: tests/suite2
install:
  - pip install .
  - pip install psutil
  - pip install -U py
  - pip install pytest-xdist
#  - pip install -r requirements.txt
# command to run tests
script: py.test -n 6 $TEST_SUITE
